In [1]:
import pandas as pd

In [2]:
# Loading the train and test datasets (With predictions)
predicted_train = pd.read_csv("datasets/predicted_train.csv")
predicted_test = pd.read_csv("datasets/predicted_test.csv")

In [3]:
predicted_train.head()

,customer_id,firstname,lastname,record_number,days_since_opened,days_since_confirmed,primary_term,final_term,days_till_primary_close,days_till_final_close,...,encoded_payment_23,encoded_payment_24,encoded_loans_account_holder_type,encoded_loans_credit_status,encoded_loans_credit_type,encoded_loans_account_currency,primary_close_flag,final_close_flag,pred_primary_close_flag,pred_final_close_flag
0,4814dfa2-45a8-46b9-8102-98ecbbec2d2a,Navya,Vasa,7,10,8,12,10,13,5,...,3.0,4.0,1,3,4,1,0,0,0.0,0.0
1,bb0abe41-cc89-4a1d-bb1c-48bd212ae00d,Azad,Warrior,5,15,6,7,6,9,1,...,3.0,4.0,1,3,4,1,0,0,0.0,0.0
2,edfd1a62-05da-4cfd-b8ae-521f05f0fd5f,Piya,Jha,1,15,17,8,5,9,1,...,3.0,4.0,1,3,4,1,0,0,0.0,0.0
3,3eaa4c2a-2316-48f4-b1b0-4aafe2286630,Rhea,Varma,11,7,2,11,13,14,8,...,3.0,4.0,1,2,4,1,0,0,0.0,0.0
4,c9a73239-baae-40eb-8855-dab07767ea86,Sahil,Dave,12,14,9,8,11,6,13,...,3.0,4.0,1,3,4,1,0,0,0.0,0.0

In [4]:
predicted_test.head()

,customer_id,firstname,lastname,record_number,days_since_opened,days_since_confirmed,primary_term,final_term,days_till_primary_close,days_till_final_close,...,encoded_payment_21,encoded_payment_22,encoded_payment_23,encoded_payment_24,encoded_loans_account_holder_type,encoded_loans_credit_status,encoded_loans_credit_type,encoded_loans_account_currency,primary_close_flag,final_close_flag
0,1dffd171-010b-4773-894f-4095077b0e31,Aradhya,Deep,14,2,13,14,2,14,6,...,3.0,3.0,3.0,NaN,1,3,4,1,0.0,0.0
1,cf0e7f8c-b22b-410c-8ad6-4a5bfd4d11cf,Anahita,Anand,17,3,6,0,1,0,4,...,0.0,0.0,0.0,1.0,1,2,3,1,0.0,0.0
2,49c9f6ef-58f2-4334-bb44-9a4ded2e587f,Amani,Tak,14,9,10,14,7,10,4,...,3.0,3.0,3.0,4.0,1,2,4,1,0.0,0.0
3,daab9520-7716-4b1e-b791-907912a81f79,Tushar,Sodhi,7,14,4,12,11,6,13,...,3.0,3.0,3.0,4.0,1,3,4,1,0.0,0.0
4,9d4adc34-368e-4642-98a2-58d73b4294f7,Jivika,Rana,13,3,3,16,1,15,4,...,3.0,3.0,3.0,4.0,1,3,3,1,0.0,0.0

# Processing Train and Test Data
For train data we can delete the following columns
1. primary_close_flag
2. final_close_flag

These columns would be basically replaced by their predicted versions.

For test data, we would keep all the columns

In [5]:
predicted_train = (predicted_train
                   .drop(["primary_close_flag", "final_close_flag"], axis=1)
                   .rename({"pred_primary_close_flag": "primary_close_flag",
                            "pred_final_close_flag": "final_close_flag"},
                           axis=1
                          )
                  )

predicted_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1106674 entries, 0 to 1106673
Data columns (total 62 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   customer_id                         1106674 non-null  object
 1   firstname                           1106674 non-null  object
 2   lastname                            1106674 non-null  object
 3   record_number                       1106674 non-null  int64
 4   days_since_opened                   1106674 non-null  int64
 5   days_since_confirmed                1106674 non-null  int64
 6   primary_term                        1106674 non-null  int64
 7   final_term                          1106674 non-null  int64
 8   days_till_primary_close             1106674 non-null  int64
 9   days_till_final_close               1106674 non-null  int64
 10  loans_credit_limit                  1106674 non-null  int64
 11  loans_next_payment_summary          1106674 non-null  int64
 12  loans_outstanding_balance           1106674 non-null  int64
 13  loans_max_overdue_amount            1106674 non-null  int64
 14  loans_credit_cost_rate              1106674 non-null  int64
 15  loans_within_5_days                 1106674 non-null  int64
 16  loans_within_5_to_30_days           1106674 non-null  int64
 17  loans_within_30_to_60_days          1106674 non-null  int64
 18  loans_within_60_to_90_days          1106674 non-null  int64
 19  loans_over_90_days                  1106674 non-null  int64
 20  is_zero_loans_within_5_days         1106674 non-null  object
 21  is_zero_loans_within_5_to_30_days   1106674 non-null  object
 22  is_zero_loans_within_30_to_60_days  1106674 non-null  object
 23  is_zero_loans_within_60_to_90_days  1106674 non-null  object
 24  is_zero_loans_over_90_days          1106674 non-null  object
 25  utilization                         1106674 non-null  int64
 26  over_limit_count                    1106674 non-null  int64
 27  max_over_limit_count                1106674 non-null  int64
 28  is_zero_utilization                 1106674 non-null  object
 29  is_zero_over_limit_count            1106674 non-null  object
 30  is_zero_max_over_limit_count        1106674 non-null  object
 31  encoded_payment_0                   1069055 non-null  float64
 32  encoded_payment_1                   1070930 non-null  float64
 33  encoded_payment_2                   1072062 non-null  float64
 34  encoded_payment_3                   1069258 non-null  float64
 35  encoded_payment_4                   1070834 non-null  float64
 36  encoded_payment_5                   1071370 non-null  float64
 37  encoded_payment_6                   1068655 non-null  float64
 38  encoded_payment_7                   1071045 non-null  float64
 39  encoded_payment_8                   1071912 non-null  float64
 40  encoded_payment_9                   1070823 non-null  float64
 41  encoded_payment_10                  1071039 non-null  float64
 42  encoded_payment_11                  1071475 non-null  float64
 43  encoded_payment_12                  1068866 non-null  float64
 44  encoded_payment_13                  1071323 non-null  float64
 45  encoded_payment_14                  1069215 non-null  float64
 46  encoded_payment_15                  1070000 non-null  float64
 47  encoded_payment_16                  1071962 non-null  float64
 48  encoded_payment_17                  1069359 non-null  float64
 49  encoded_payment_18                  1071406 non-null  float64
 50  encoded_payment_19                  1070293 non-null  float64
 51  encoded_payment_20                  1069155 non-null  float64
 52  encoded_payment_21                  1069126 non-null  float64
 53  encoded_payment_22                  1069519 non-null  float64
 54  encoded_payment_23                  1070131 non-null  float64
 55  encoded_payment_24                  1070629 non-null  float64
 56  encoded_loans_account_holder_type   1106674 non-null  int64
 57  encoded_loans_credit_status         1106674 non-null  int64
 58  encoded_loans_credit_type           1106674 non-null  int64
 59  encoded_loans_account_currency      1106674 non-null  int64
 60  primary_close_flag                  1106674 non-null  float64
 61  final_close_flag                    1106674 non-null  float64
dtypes: float64(27), int64(24), object(11)
memory usage: 523.5+ MB

In [6]:
predicted_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474289 entries, 0 to 474288
Data columns (total 62 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   customer_id                         474289 non-null  object
 1   firstname                           474289 non-null  object
 2   lastname                            474289 non-null  object
 3   record_number                       474289 non-null  int64
 4   days_since_opened                   474289 non-null  int64
 5   days_since_confirmed                474289 non-null  int64
 6   primary_term                        474289 non-null  int64
 7   final_term                          474289 non-null  int64
 8   days_till_primary_close             474289 non-null  int64
 9   days_till_final_close               474289 non-null  int64
 10  loans_credit_limit                  474289 non-null  int64
 11  loans_next_payment_summary          474289 non-null  int64
 12  loans_outstanding_balance           474289 non-null  int64
 13  loans_max_overdue_amount            474289 non-null  int64
 14  loans_credit_cost_rate              474289 non-null  int64
 15  loans_within_5_days                 474289 non-null  int64
 16  loans_within_5_to_30_days           474289 non-null  int64
 17  loans_within_30_to_60_days          474289 non-null  int64
 18  loans_within_60_to_90_days          474289 non-null  int64
 19  loans_over_90_days                  474289 non-null  int64
 20  is_zero_loans_within_5_days         474289 non-null  object
 21  is_zero_loans_within_5_to_30_days   474289 non-null  object
 22  is_zero_loans_within_30_to_60_days  474289 non-null  object
 23  is_zero_loans_within_60_to_90_days  474289 non-null  object
 24  is_zero_loans_over_90_days          474289 non-null  object
 25  utilization                         474289 non-null  int64
 26  over_limit_count                    474289 non-null  int64
 27  max_over_limit_count                474289 non-null  int64
 28  is_zero_utilization                 474289 non-null  object
 29  is_zero_over_limit_count            474289 non-null  object
 30  is_zero_max_over_limit_count        474289 non-null  object
 31  encoded_payment_0                   458297 non-null  float64
 32  encoded_payment_1                   458668 non-null  float64
 33  encoded_payment_2                   459311 non-null  float64
 34  encoded_payment_3                   458068 non-null  float64
 35  encoded_payment_4                   458761 non-null  float64
 36  encoded_payment_5                   459257 non-null  float64
 37  encoded_payment_6                   458067 non-null  float64
 38  encoded_payment_7                   459064 non-null  float64
 39  encoded_payment_8                   459325 non-null  float64
 40  encoded_payment_9                   458736 non-null  float64
 41  encoded_payment_10                  459001 non-null  float64
 42  encoded_payment_11                  459428 non-null  float64
 43  encoded_payment_12                  458041 non-null  float64
 44  encoded_payment_13                  459216 non-null  float64
 45  encoded_payment_14                  458036 non-null  float64
 46  encoded_payment_15                  458625 non-null  float64
 47  encoded_payment_16                  459365 non-null  float64
 48  encoded_payment_17                  458153 non-null  float64
 49  encoded_payment_18                  459429 non-null  float64
 50  encoded_payment_19                  458580 non-null  float64
 51  encoded_payment_20                  458035 non-null  float64
 52  encoded_payment_21                  458386 non-null  float64
 53  encoded_payment_22                  458579 non-null  float64
 54  encoded_payment_23                  458777 non-null  float64
 55  encoded_payment_24                  458908 non-null  float64
 56  encoded_loans_account_holder_type   474289 non-null  int64
 57  encoded_loans_credit_status         474289 non-null  int64
 58  encoded_loans_credit_type           474289 non-null  int64
 59  encoded_loans_account_currency      474289 non-null  int64
 60  primary_close_flag                  474289 non-null  float64
 61  final_close_flag                    474289 non-null  float64
dtypes: float64(27), int64(24), object(11)
memory usage: 224.3+ MB

# Concatenating Train and Test

In [7]:
final_df = pd.concat([predicted_train, predicted_test])
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1580963 entries, 0 to 474288
Data columns (total 62 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   customer_id                         1580963 non-null  object
 1   firstname                           1580963 non-null  object
 2   lastname                            1580963 non-null  object
 3   record_number                       1580963 non-null  int64
 4   days_since_opened                   1580963 non-null  int64
 5   days_since_confirmed                1580963 non-null  int64
 6   primary_term                        1580963 non-null  int64
 7   final_term                          1580963 non-null  int64
 8   days_till_primary_close             1580963 non-null  int64
 9   days_till_final_close               1580963 non-null  int64
 10  loans_credit_limit                  1580963 non-null  int64
 11  loans_next_payment_summary          1580963 non-null  int64
 12  loans_outstanding_balance           1580963 non-null  int64
 13  loans_max_overdue_amount            1580963 non-null  int64
 14  loans_credit_cost_rate              1580963 non-null  int64
 15  loans_within_5_days                 1580963 non-null  int64
 16  loans_within_5_to_30_days           1580963 non-null  int64
 17  loans_within_30_to_60_days          1580963 non-null  int64
 18  loans_within_60_to_90_days          1580963 non-null  int64
 19  loans_over_90_days                  1580963 non-null  int64
 20  is_zero_loans_within_5_days         1580963 non-null  object
 21  is_zero_loans_within_5_to_30_days   1580963 non-null  object
 22  is_zero_loans_within_30_to_60_days  1580963 non-null  object
 23  is_zero_loans_within_60_to_90_days  1580963 non-null  object
 24  is_zero_loans_over_90_days          1580963 non-null  object
 25  utilization                         1580963 non-null  int64
 26  over_limit_count                    1580963 non-null  int64
 27  max_over_limit_count                1580963 non-null  int64
 28  is_zero_utilization                 1580963 non-null  object
 29  is_zero_over_limit_count            1580963 non-null  object
 30  is_zero_max_over_limit_count        1580963 non-null  object
 31  encoded_payment_0                   1527352 non-null  float64
 32  encoded_payment_1                   1529598 non-null  float64
 33  encoded_payment_2                   1531373 non-null  float64
 34  encoded_payment_3                   1527326 non-null  float64
 35  encoded_payment_4                   1529595 non-null  float64
 36  encoded_payment_5                   1530627 non-null  float64
 37  encoded_payment_6                   1526722 non-null  float64
 38  encoded_payment_7                   1530109 non-null  float64
 39  encoded_payment_8                   1531237 non-null  float64
 40  encoded_payment_9                   1529559 non-null  float64
 41  encoded_payment_10                  1530040 non-null  float64
 42  encoded_payment_11                  1530903 non-null  float64
 43  encoded_payment_12                  1526907 non-null  float64
 44  encoded_payment_13                  1530539 non-null  float64
 45  encoded_payment_14                  1527251 non-null  float64
 46  encoded_payment_15                  1528625 non-null  float64
 47  encoded_payment_16                  1531327 non-null  float64
 48  encoded_payment_17                  1527512 non-null  float64
 49  encoded_payment_18                  1530835 non-null  float64
 50  encoded_payment_19                  1528873 non-null  float64
 51  encoded_payment_20                  1527190 non-null  float64
 52  encoded_payment_21                  1527512 non-null  float64
 53  encoded_payment_22                  1528098 non-null  float64
 54  encoded_payment_23                  1528908 non-null  float64
 55  encoded_payment_24                  1529537 non-null  float64
 56  encoded_loans_account_holder_type   1580963 non-null  int64
 57  encoded_loans_credit_status         1580963 non-null  int64
 58  encoded_loans_credit_type           1580963 non-null  int64
 59  encoded_loans_account_currency      1580963 non-null  int64
 60  primary_close_flag                  1580963 non-null  float64
 61  final_close_flag                    1580963 non-null  float64
dtypes: float64(27), int64(24), object(11)
memory usage: 759.9+ MB

In [8]:
# Saving as CSV
final_df.to_csv("datasets/loan_application_data_combined.csv",index=False)`

In [11]:
!pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in s:\anaconda\anaconda3\lib\site-packages (2.0.22)
Requirement already satisfied: pyodbc in s:\anaconda\anaconda3\lib\site-packages (4.0.32)
Requirement already satisfied: greenlet!=0.4.17 in s:\anaconda\anaconda3\lib\site-packages (from sqlalchemy) (1.1.1)
Requirement already satisfied: typing-extensions>=4.2.0 in s:\anaconda\anaconda3\lib\site-packages (from sqlalchemy) (4.8.0)

In [2]:
# import pandas as pd
# import pyodbc
# from sqlalchemy import create_engine
# from tqdm import tqdm
# import concurrent.futures

# username='sumit'
# password='admin123'
# server='SUMIT-PC\SQLEXPRESS'
# database='loandefault_db'

# # Create a SQLAlchemy engine to connect to the SQL Server database
# engine = create_engine(f'mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server')

# engine

Engine(mssql+pyodbc://sumit:***@SUMIT-PC\SQLEXPRESS/loandefault_db?driver=ODBC+Driver+17+for+SQL+Server)

In [3]:
# final_df = pd.read_csv("datasets/loan_application_data_combined.csv")
# final_df.shape

(1580963, 62)

In [4]:
# table_name = 'loan_application_data'  # Replace with your desired table name

# # final_df.to_sql(table_name, engine, if_exists='replace', index=False)

In [5]:
# import logging

# # Configure the logging settings
# logging.basicConfig(filename='data_loading.log', level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
# logger = logging.getLogger(__name__)

In [7]:
# def insert_data_async(chunk):
#     try:
#         chunk.to_sql(table_name, engine, if_exists='append', index=False)
#     except Exception as e:
#         logger.error(f"Error during data insertion: {e}")

# # Split the DataFrame into smaller chunks
# chunk_size = int(len(final_df)/4)  # You can adjust the chunk size as needed
# df_chunks = [final_df[i:i + chunk_size] for i in range(0, len(final_df), chunk_size)]

# # Calculate the total number of rows in the DataFrame
# total_rows = len(final_df)

# # Create a progress bar using tqdm
# with tqdm(total=total_rows, unit='row', unit_scale=True) as pbar:
#     # Define a callback function to update the progress bar
#     def callback(index):
#         pbar.update(1)

#     # Use a ThreadPoolExecutor to insert data asynchronously
#     with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
#         futures = [executor.submit(insert_data_async, chunk) for chunk in df_chunks]

#     # Wait for all asynchronous inserts to complete
#     concurrent.futures.wait(futures)

# # Close the database connection
# engine.dispose()

# # Log a message when the data loading is complete
# logger.info("Data loading complete.")

In [1]:
import chainlit as cl
from sql import sql_query_engine
from llm import llm, embed_model
from llama_index.callbacks import CallbackManager, LlamaDebugHandler

from llama_index.tools import QueryEngineTool, ToolMetadata
from llama_index.query_engine import SubQuestionQueryEngine
from llama_index import set_global_service_context, ServiceContext


# llama_debug = LlamaDebugHandler(print_trace_on_end=True)
# callback_manager = CallbackManager([llama_debug])
# service_context = ServiceContext.from_defaults(callback_manager=callback_manager, 
                                        #        llm=llm, embed_model=embed_model)

service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)

set_global_service_context(service_context)

query_engine_tools = [
        QueryEngineTool(
                query_engine=sql_query_engine,
                metadata = ToolMetadata(
                        name="Customer Loan Database",
                        description= '''
                        Database containing the Loan Application Data table
                        '''
                )
        )
]

subquery_engine = SubQuestionQueryEngine.from_defaults(query_engine_tools=query_engine_tools,
                                                       service_context = service_context,
                                                       use_async = True, verbose=True
                                                       )

response = subquery_engine.query('what is the average and total loan amount. Also tell me about the unique number of applicants.')

Sql database created...
Object index created..
Query Engine created..
Generated 3 sub questions.
[Customer Loan Database] Q: What is the average loan amount?
2023-11-05 13:29:13 - > Table desc str: Table 'loan_application_data' has columns: customer_id (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), firstname (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), lastname (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), record_number (TINYINT), days_since_opened (TINYINT), days_since_confirmed (TINYINT), primary_term (TINYINT), final_term (TINYINT), days_till_primary_close (TINYINT), days_till_final_close (TINYINT), loans_credit_limit (TINYINT), loans_next_payment_summary (TINYINT), loans_outstanding_balance (TINYINT), loans_max_overdue_amount (TINYINT), loans_credit_cost_rate (TINYINT), loans_within_5_days (TINYINT), loans_within_5_to_30_days (TINYINT), loans_within_30_to_60_days (TINYINT), loans_within_60_to_90_days (TINYINT), loans_over_90_days (TINYINT), is_zero_loans_within_5_days (BIT), is_zero_loans_within_5_to_30_days (BIT), is_zero_loans_within_30_to_60_days (BIT), is_zero_loans_within_60_to_90_days (BIT), is_zero_loans_over_90_days (BIT), utilization (TINYINT), over_limit_count (TINYINT), max_over_limit_count (TINYINT), is_zero_utilization (BIT), is_zero_over_limit_count (BIT), is_zero_max_over_limit_count (BIT), encoded_payment_0 (FLOAT), encoded_payment_1 (FLOAT), encoded_payment_2 (FLOAT), encoded_payment_3 (FLOAT), encoded_payment_4 (FLOAT), encoded_payment_5 (FLOAT), encoded_payment_6 (FLOAT), encoded_payment_7 (FLOAT), encoded_payment_8 (FLOAT), encoded_payment_9 (FLOAT), encoded_payment_10 (FLOAT), encoded_payment_11 (FLOAT), encoded_payment_12 (FLOAT), encoded_payment_13 (FLOAT), encoded_payment_14 (FLOAT), encoded_payment_15 (FLOAT), encoded_payment_16 (FLOAT), encoded_payment_17 (FLOAT), encoded_payment_18 (FLOAT), encoded_payment_19 (FLOAT), encoded_payment_20 (FLOAT), encoded_payment_21 (FLOAT), encoded_payment_22 (FLOAT), encoded_payment_23 (FLOAT), encoded_payment_24 (FLOAT), encoded_loans_account_holder_type (TINYINT), encoded_loans_credit_status (TINYINT), encoded_loans_credit_type (TINYINT), encoded_loans_account_currency (TINYINT), primary_close_flag (FLOAT), final_close_flag (FLOAT), and foreign keys: . The table description is:
                        Please refer to this table's column description to get the loan details.

                        ####
                        Dataset Description

The dataset provided to the participants will contain:

#Customer Information:

customer_id: Unique identifier for each customer application.
firstname: First name of the customer.
lastname: Last name of the customer.

#Credit Record Information:

record_number: Sequence number of the credit product in the credit history.
days_since_opened: Days from credit opening date to data collection date.
days_since_confirmed: Days from credit information confirmation date till data collection date.
primary_term: Planned number of days from credit opening date to closing date.
final_term: Actual number of days from credit opening date to closing date.
days_till_primary_close: Planned number of days from data collection date until loan closing date.
days_till_final_close: Actual number of days from data collection date until loan closing date.
loans_credit_limit: Credit limit for the customer's loans.
loans_next_payment_summary: Amount of the next loan payment.
loans_outstanding_balance: Outstanding balance amount.
loans_max_overdue_amount: Maximum overdue amount.
loans_credit_cost_rate: Cost rate associated with loans.
Loan Overdue Information:

loans_within_5_days to loans_over_90_days: Number of loans overdue within different time frames.
is_zero_loans_within_5_days to is_zero_loans_over_90_days: Binary indicators for zero loans overdue within different time frames.

#Credit Utilization and Limit Information:

utilization: Credit utilization rate.
over_limit_count: Count of instances where the customer went over the credit limit.
max_over_limit_count: Maximum count of instances where the customer exceeded the credit limit.
is_zero_utilization: Binary indicator if credit utilization rate is zero.
is_zero_over_limit_count: Binary indicator if the count of over limit instances is zero.
is_zero_max_over_limit_count: Binary indicator if the maximum over limit count is zero.


#Encoded Features:

encoded_payment_X: Encoded information about payment X (categorical features converted to numerical values).
encoded_loans_account_holder_type: Encoded information about the type of account holder for loans.
encoded_loans_credit_status: Encoded information about the credit status of loans.
encoded_loans_credit_type: Encoded information about the type of credit for loans.
encoded_loans_account_currency: Encoded information about the currency used for loans.

#Close Flags:

primary_close_flag: Binary indicator for primary term close.
final_close_flag: Binary indicator for final term close.

###


[Customer Loan Database] Q: What is the total loan amount?
2023-11-05 13:29:14 - > Table desc str: Table 'loan_application_data' has columns: customer_id (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), firstname (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), lastname (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), record_number (TINYINT), days_since_opened (TINYINT), days_since_confirmed (TINYINT), primary_term (TINYINT), final_term (TINYINT), days_till_primary_close (TINYINT), days_till_final_close (TINYINT), loans_credit_limit (TINYINT), loans_next_payment_summary (TINYINT), loans_outstanding_balance (TINYINT), loans_max_overdue_amount (TINYINT), loans_credit_cost_rate (TINYINT), loans_within_5_days (TINYINT), loans_within_5_to_30_days (TINYINT), loans_within_30_to_60_days (TINYINT), loans_within_60_to_90_days (TINYINT), loans_over_90_days (TINYINT), is_zero_loans_within_5_days (BIT), is_zero_loans_within_5_to_30_days (BIT), is_zero_loans_within_30_to_60_days (BIT), is_zero_loans_within_60_to_90_days (BIT), is_zero_loans_over_90_days (BIT), utilization (TINYINT), over_limit_count (TINYINT), max_over_limit_count (TINYINT), is_zero_utilization (BIT), is_zero_over_limit_count (BIT), is_zero_max_over_limit_count (BIT), encoded_payment_0 (FLOAT), encoded_payment_1 (FLOAT), encoded_payment_2 (FLOAT), encoded_payment_3 (FLOAT), encoded_payment_4 (FLOAT), encoded_payment_5 (FLOAT), encoded_payment_6 (FLOAT), encoded_payment_7 (FLOAT), encoded_payment_8 (FLOAT), encoded_payment_9 (FLOAT), encoded_payment_10 (FLOAT), encoded_payment_11 (FLOAT), encoded_payment_12 (FLOAT), encoded_payment_13 (FLOAT), encoded_payment_14 (FLOAT), encoded_payment_15 (FLOAT), encoded_payment_16 (FLOAT), encoded_payment_17 (FLOAT), encoded_payment_18 (FLOAT), encoded_payment_19 (FLOAT), encoded_payment_20 (FLOAT), encoded_payment_21 (FLOAT), encoded_payment_22 (FLOAT), encoded_payment_23 (FLOAT), encoded_payment_24 (FLOAT), encoded_loans_account_holder_type (TINYINT), encoded_loans_credit_status (TINYINT), encoded_loans_credit_type (TINYINT), encoded_loans_account_currency (TINYINT), primary_close_flag (FLOAT), final_close_flag (FLOAT), and foreign keys: . The table description is:
                        Please refer to this table's column description to get the loan details.

                        ####
                        Dataset Description

The dataset provided to the participants will contain:

#Customer Information:

customer_id: Unique identifier for each customer application.
firstname: First name of the customer.
lastname: Last name of the customer.

#Credit Record Information:

record_number: Sequence number of the credit product in the credit history.
days_since_opened: Days from credit opening date to data collection date.
days_since_confirmed: Days from credit information confirmation date till data collection date.
primary_term: Planned number of days from credit opening date to closing date.
final_term: Actual number of days from credit opening date to closing date.
days_till_primary_close: Planned number of days from data collection date until loan closing date.
days_till_final_close: Actual number of days from data collection date until loan closing date.
loans_credit_limit: Credit limit for the customer's loans.
loans_next_payment_summary: Amount of the next loan payment.
loans_outstanding_balance: Outstanding balance amount.
loans_max_overdue_amount: Maximum overdue amount.
loans_credit_cost_rate: Cost rate associated with loans.
Loan Overdue Information:

loans_within_5_days to loans_over_90_days: Number of loans overdue within different time frames.
is_zero_loans_within_5_days to is_zero_loans_over_90_days: Binary indicators for zero loans overdue within different time frames.

#Credit Utilization and Limit Information:

utilization: Credit utilization rate.
over_limit_count: Count of instances where the customer went over the credit limit.
max_over_limit_count: Maximum count of instances where the customer exceeded the credit limit.
is_zero_utilization: Binary indicator if credit utilization rate is zero.
is_zero_over_limit_count: Binary indicator if the count of over limit instances is zero.
is_zero_max_over_limit_count: Binary indicator if the maximum over limit count is zero.


#Encoded Features:

encoded_payment_X: Encoded information about payment X (categorical features converted to numerical values).
encoded_loans_account_holder_type: Encoded information about the type of account holder for loans.
encoded_loans_credit_status: Encoded information about the credit status of loans.
encoded_loans_credit_type: Encoded information about the type of credit for loans.
encoded_loans_account_currency: Encoded information about the currency used for loans.

#Close Flags:

primary_close_flag: Binary indicator for primary term close.
final_close_flag: Binary indicator for final term close.

###


[Customer Loan Database] Q: How many unique applicants are there?
2023-11-05 13:29:14 - > Table desc str: Table 'loan_application_data' has columns: customer_id (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), firstname (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), lastname (NVARCHAR(50) COLLATE "SQL_Latin1_General_CP1_CI_AS"), record_number (TINYINT), days_since_opened (TINYINT), days_since_confirmed (TINYINT), primary_term (TINYINT), final_term (TINYINT), days_till_primary_close (TINYINT), days_till_final_close (TINYINT), loans_credit_limit (TINYINT), loans_next_payment_summary (TINYINT), loans_outstanding_balance (TINYINT), loans_max_overdue_amount (TINYINT), loans_credit_cost_rate (TINYINT), loans_within_5_days (TINYINT), loans_within_5_to_30_days (TINYINT), loans_within_30_to_60_days (TINYINT), loans_within_60_to_90_days (TINYINT), loans_over_90_days (TINYINT), is_zero_loans_within_5_days (BIT), is_zero_loans_within_5_to_30_days (BIT), is_zero_loans_within_30_to_60_days (BIT), is_zero_loans_within_60_to_90_days (BIT), is_zero_loans_over_90_days (BIT), utilization (TINYINT), over_limit_count (TINYINT), max_over_limit_count (TINYINT), is_zero_utilization (BIT), is_zero_over_limit_count (BIT), is_zero_max_over_limit_count (BIT), encoded_payment_0 (FLOAT), encoded_payment_1 (FLOAT), encoded_payment_2 (FLOAT), encoded_payment_3 (FLOAT), encoded_payment_4 (FLOAT), encoded_payment_5 (FLOAT), encoded_payment_6 (FLOAT), encoded_payment_7 (FLOAT), encoded_payment_8 (FLOAT), encoded_payment_9 (FLOAT), encoded_payment_10 (FLOAT), encoded_payment_11 (FLOAT), encoded_payment_12 (FLOAT), encoded_payment_13 (FLOAT), encoded_payment_14 (FLOAT), encoded_payment_15 (FLOAT), encoded_payment_16 (FLOAT), encoded_payment_17 (FLOAT), encoded_payment_18 (FLOAT), encoded_payment_19 (FLOAT), encoded_payment_20 (FLOAT), encoded_payment_21 (FLOAT), encoded_payment_22 (FLOAT), encoded_payment_23 (FLOAT), encoded_payment_24 (FLOAT), encoded_loans_account_holder_type (TINYINT), encoded_loans_credit_status (TINYINT), encoded_loans_credit_type (TINYINT), encoded_loans_account_currency (TINYINT), primary_close_flag (FLOAT), final_close_flag (FLOAT), and foreign keys: . The table description is:
                        Please refer to this table's column description to get the loan details.

                        ####
                        Dataset Description

The dataset provided to the participants will contain:

#Customer Information:

customer_id: Unique identifier for each customer application.
firstname: First name of the customer.
lastname: Last name of the customer.

#Credit Record Information:

record_number: Sequence number of the credit product in the credit history.
days_since_opened: Days from credit opening date to data collection date.
days_since_confirmed: Days from credit information confirmation date till data collection date.
primary_term: Planned number of days from credit opening date to closing date.
final_term: Actual number of days from credit opening date to closing date.
days_till_primary_close: Planned number of days from data collection date until loan closing date.
days_till_final_close: Actual number of days from data collection date until loan closing date.
loans_credit_limit: Credit limit for the customer's loans.
loans_next_payment_summary: Amount of the next loan payment.
loans_outstanding_balance: Outstanding balance amount.
loans_max_overdue_amount: Maximum overdue amount.
loans_credit_cost_rate: Cost rate associated with loans.
Loan Overdue Information:

loans_within_5_days to loans_over_90_days: Number of loans overdue within different time frames.
is_zero_loans_within_5_days to is_zero_loans_over_90_days: Binary indicators for zero loans overdue within different time frames.

#Credit Utilization and Limit Information:

utilization: Credit utilization rate.
over_limit_count: Count of instances where the customer went over the credit limit.
max_over_limit_count: Maximum count of instances where the customer exceeded the credit limit.
is_zero_utilization: Binary indicator if credit utilization rate is zero.
is_zero_over_limit_count: Binary indicator if the count of over limit instances is zero.
is_zero_max_over_limit_count: Binary indicator if the maximum over limit count is zero.


#Encoded Features:

encoded_payment_X: Encoded information about payment X (categorical features converted to numerical values).
encoded_loans_account_holder_type: Encoded information about the type of account holder for loans.
encoded_loans_credit_status: Encoded information about the credit status of loans.
encoded_loans_credit_type: Encoded information about the type of credit for loans.
encoded_loans_account_currency: Encoded information about the currency used for loans.

#Close Flags:

primary_close_flag: Binary indicator for primary term close.
final_close_flag: Binary indicator for final term close.

###


2023-11-05 13:29:16 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=1122 request_id=c8a3cd7a491e0bf188618043ff96ca77 response_code=200
2023-11-05 13:29:17 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=1510 request_id=0ad77eabbcbaca8fefadaffc5aa6dd38 response_code=200
2023-11-05 13:29:17 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=1273 request_id=e03d5f6bc247c439b09802a105a56ec1 response_code=200
2023-11-05 13:29:19 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=356 request_id=35c2280cf6d1ac24891daa66f55318e0 response_code=200
[Customer Loan Database] A: The average loan amount is $2.
2023-11-05 13:29:19 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=219 request_id=505420b9bc2283be71e540cb6a6890d5 response_code=200
[Customer Loan Database] A: There are 98,376 unique applicants.
2023-11-05 13:29:19 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=304 request_id=d40e00e5304309c9aba5f84ced1dd5f5 response_code=200
[Customer Loan Database] A: The total loan amount is $4,731,399.

In [3]:
response

Response(response='The average loan amount is $2 and the total loan amount is $4,731,399. There are 98,376 unique applicants.', source_nodes=[NodeWithScore(node=TextNode(id_='1df9b6a5-7601-41f5-819d-f05183872f9b', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='7a946c519c899d8ea9680c663b7f7d8eeacf339e75339c487c23ed11e87e2246', text='Sub question: What is the average loan amount?\nResponse: The average loan amount is $2.', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='cf7caffb-b531-4cee-b67d-1a6171f2bb20', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='3104366d08934f66e41e2ce576fffeea24eda4d8b14c15d753f21ff3302746b3', text='Sub question: What is the total loan amount?\nResponse: The total loan amount is $4,731,399.', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='85d4424b-b646-471e-8b98-a310b7afd8e9', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='72149c566662046ebb8172f71edb47980630af5c51f08cdd8189cc8f4bbceeda', text='Sub question: How many unique applicants are there?\nResponse: There are 98,376 unique applicants.', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='83dd23cc-6fe4-4678-9bbf-202cdf1f0b79', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='ab196c083b0d6c3d997bcb24609277076fec46dd800e2ea6addf63d9350cd603', text='[(2,)]', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='0ee27767-872a-45f1-bc72-419ccfeb6b97', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='9bd35641d15afaae2237fa2cf2c45a059cb4f17d014ce2ee1c9f1f97bc1ceb02', text='[(4731399,)]', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='abbbb9d4-8372-4f9b-8da1-b21ec57ab709', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='1df56c2504f5d3c54fb8f72dbe47bf7595a428d00a27cafd79a5eac734fb1143', text='[(98376,)]', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None)], metadata={'1df9b6a5-7601-41f5-819d-f05183872f9b': {}, 'cf7caffb-b531-4cee-b67d-1a6171f2bb20': {}, '85d4424b-b646-471e-8b98-a310b7afd8e9': {}, '83dd23cc-6fe4-4678-9bbf-202cdf1f0b79': {}, '0ee27767-872a-45f1-bc72-419ccfeb6b97': {}, 'abbbb9d4-8372-4f9b-8da1-b21ec57ab709': {}})

In [5]:
response.get_formatted_sources

<bound method Response.get_formatted_sources of Response(response='The average loan amount is $2 and the total loan amount is $4,731,399. There are 98,376 unique applicants.', source_nodes=[NodeWithScore(node=TextNode(id_='1df9b6a5-7601-41f5-819d-f05183872f9b', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='7a946c519c899d8ea9680c663b7f7d8eeacf339e75339c487c23ed11e87e2246', text='Sub question: What is the average loan amount?\nResponse: The average loan amount is $2.', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='cf7caffb-b531-4cee-b67d-1a6171f2bb20', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='3104366d08934f66e41e2ce576fffeea24eda4d8b14c15d753f21ff3302746b3', text='Sub question: What is the total loan amount?\nResponse: The total loan amount is $4,731,399.', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='85d4424b-b646-471e-8b98-a310b7afd8e9', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='72149c566662046ebb8172f71edb47980630af5c51f08cdd8189cc8f4bbceeda', text='Sub question: How many unique applicants are there?\nResponse: There are 98,376 unique applicants.', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='83dd23cc-6fe4-4678-9bbf-202cdf1f0b79', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='ab196c083b0d6c3d997bcb24609277076fec46dd800e2ea6addf63d9350cd603', text='[(2,)]', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='0ee27767-872a-45f1-bc72-419ccfeb6b97', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='9bd35641d15afaae2237fa2cf2c45a059cb4f17d014ce2ee1c9f1f97bc1ceb02', text='[(4731399,)]', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None), NodeWithScore(node=TextNode(id_='abbbb9d4-8372-4f9b-8da1-b21ec57ab709', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='1df56c2504f5d3c54fb8f72dbe47bf7595a428d00a27cafd79a5eac734fb1143', text='[(98376,)]', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None)], metadata={'1df9b6a5-7601-41f5-819d-f05183872f9b': {}, 'cf7caffb-b531-4cee-b67d-1a6171f2bb20': {}, '85d4424b-b646-471e-8b98-a310b7afd8e9': {}, '83dd23cc-6fe4-4678-9bbf-202cdf1f0b79': {}, '0ee27767-872a-45f1-bc72-419ccfeb6b97': {}, 'abbbb9d4-8372-4f9b-8da1-b21ec57ab709': {}})>